server:
  port: 8085

products:
  number: 1000
  load: true

logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: DEBUG

spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver